version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 10s
      timeout: 10s
      retries: 5
    
  cloudservice:
    image: sannidhi09/pixelgram_cloud_service
    ports:
      - "5004:5004"
    tty: true
    restart: on-failure
    depends_on:
      - rabbitmq
    
  userservice:
    build: sannidhi09/pixelgram_user_service
    ports:
      - "5003:5003"
    tty: true
    restart: on-failure
    
  getwayservice:
    build: sannidhi09/pixelgram_gateway_service
    ports:
      - "5000:5000"
    tty: true
    restart: on-failure

  metadataservice:
    build: sannidhi09/pixelgram_metadata_service
    ports:
      - "5006:5006"
    tty: true
    restart: on-failure
    depends_on:
      - rabbitmq
      - cloudservice

  imageservice:
    build: sannidhi09/pixelgram_image_service
    ports:
      - "5005:5005"
    tty: true
    restart: on-failure
    depends_on:
      - rabbitmq
      - cloudservice
      - metadataservice

  ui:
    build: sannidhi09/pixelgram_ui_service
    ports:
      - "3000:3000"
    tty: true
    restart: on-failure
    depends_on:
      - getwayservice
